// <auto-generated />
namespace _12246765_OnlineStore.Migrations.StoreConfiguration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addorders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addorders));
        
        string IMigrationMetadata.Id
        {
            get { return "202101300722062_addorders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
